-- MySQL Script generated by MySQL Workbench
-- Sat 30 May 2026 01:08:15 PM MSK
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USERS` ;

CREATE TABLE IF NOT EXISTS `USERS` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL,
  `password` VARCHAR(255) NOT NULL,
  `two_factor_secret` TEXT NULL,
  `two_factor_secret_codes` TEXT NULL,
  `remember_token` VARCHAR(100) NULL,
  `current_team_id` BIGINT(20) NULL,
  `profile_photo_path` VARCHAR(2048) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `current_team_id_UNIQUE` (`current_team_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `informants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `informants` ;

CREATE TABLE IF NOT EXISTS `informants` (
  `id` SMALLINT(5) UNSIGNED NOT NULL,
  `birth_date` SMALLINT(5) UNSIGNED NULL,
  `name_en` VARCHAR(150) NULL,
  `name_ru` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_place_date` (`birth_date` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `regions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `regions` ;

CREATE TABLE IF NOT EXISTS `regions` (
  `id` TINYINT(3) UNSIGNED NOT NULL,
  `name_ru` VARCHAR(150) COLLATE 'Default Collation' NOT NULL COMMENT 'Russian name',
  `name_en` VARCHAR(150) COLLATE 'Default Collation' NULL DEFAULT NULL COMMENT 'English name',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `districts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `districts` ;

CREATE TABLE IF NOT EXISTS `districts` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `region_id` TINYINT UNSIGNED NOT NULL,
  `name_ru` VARCHAR(150) NOT NULL COMMENT 'Russian name',
  `name_en` VARCHAR(150) NULL COMMENT 'English name',
  `foundation` SMALLINT UNSIGNED NULL COMMENT 'Year of foundation of this region.',
  `abolition` SMALLINT UNSIGNED NULL COMMENT 'Year of abolition (end of life) of this region.',
  `wd` INT UNSIGNED NULL DEFAULT NULL COMMENT 'Wikidata identifier',
  PRIMARY KEY (`id`),
  INDEX `fk_region_idx` (`region_id` ASC) VISIBLE,
  CONSTRAINT `fk_region`
    FOREIGN KEY (`region_id`)
    REFERENCES `regions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Справочник районов (современное местоположение)';


-- -----------------------------------------------------
-- Table `geotypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geotypes` ;

CREATE TABLE IF NOT EXISTS `geotypes` (
  `id` TINYINT(3) UNSIGNED NOT NULL COMMENT 'id',
  `short_ru` VARCHAR(32) NULL DEFAULT NULL COMMENT 'Short description in Russian',
  `name_ru` VARCHAR(64) NOT NULL COMMENT 'Name in Russian',
  `desc_ru` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Description in Russian',
  `short_en` VARCHAR(32) NULL DEFAULT NULL COMMENT 'Short description in English',
  `name_en` VARCHAR(64) NULL DEFAULT NULL COMMENT 'Name in English',
  `desc_en` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Description in English',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `short_ru_UNIQUE` (`short_ru` ASC) VISIBLE,
  UNIQUE INDEX `short_en_UNIQUE` (`short_en` ASC) VISIBLE,
  UNIQUE INDEX `name_en_UNIQUE` (`name_en` ASC) VISIBLE,
  UNIQUE INDEX `name_ru_UNIQUE` (`name_ru` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Types of geographic objects (geo features).';


-- -----------------------------------------------------
-- Table `settlements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `settlements` ;

CREATE TABLE IF NOT EXISTS `settlements` (
  `id` SMALLINT(5) UNSIGNED NOT NULL,
  `geotype_id` TINYINT(3) UNSIGNED NULL,
  `name_ru` VARCHAR(150) NOT NULL COMMENT 'Russian name',
  `name_en` VARCHAR(150) NULL DEFAULT NULL COMMENT 'English name',
  `name_krl` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Karelian name',
  `wd` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Wikidata identifier',
  `latitude` DECIMAL(17,14) NULL DEFAULT NULL COMMENT 'Year of foundation of this settlement.',
  `longitude` DECIMAL(17,14) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_geotype_id_idx` (`geotype_id` ASC) VISIBLE,
  CONSTRAINT `fk_geotype_id`
    FOREIGN KEY (`geotype_id`)
    REFERENCES `geotypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Справочник населенных пунктов, также современных.';


-- -----------------------------------------------------
-- Table `district_settlement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `district_settlement` ;

CREATE TABLE IF NOT EXISTS `district_settlement` (
  `district_id` TINYINT(3) UNSIGNED NOT NULL,
  `settlement_id` SMALLINT(5) UNSIGNED NOT NULL,
  `include_from` SMALLINT(5) UNSIGNED NULL COMMENT 'Start year of inclusion settlement to district.',
  `include_to` SMALLINT(5) UNSIGNED NULL COMMENT 'End year of inclusion settlement to district.',
  INDEX `district_idx` (`district_id` ASC) VISIBLE,
  INDEX `settlement_idx` (`settlement_id` ASC) VISIBLE,
  CONSTRAINT `fk_district`
    FOREIGN KEY (`district_id`)
    REFERENCES `districts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_settlement`
    FOREIGN KEY (`settlement_id`)
    REFERENCES `settlements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `recorders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recorders` ;

CREATE TABLE IF NOT EXISTS `recorders` (
  `id` SMALLINT(5) UNSIGNED NOT NULL,
  `name_en` VARCHAR(150) NOT NULL,
  `name_ru` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `districts1926`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `districts1926` ;

CREATE TABLE IF NOT EXISTS `districts1926` (
  `id` TINYINT(3) UNSIGNED NOT NULL COMMENT 'id',
  `region_id` TINYINT(3) UNSIGNED NOT NULL COMMENT 'region_id',
  `name_ru` VARCHAR(150) NOT NULL COMMENT 'name_ru',
  `name_en` VARCHAR(150) NULL DEFAULT NULL,
  `wd` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Wikidata identifier',
  PRIMARY KEY (`id`),
  INDEX `fk_region_idx` (`region_id` ASC) VISIBLE,
  CONSTRAINT `fk_region0`
    FOREIGN KEY (`region_id`)
    REFERENCES `regions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Справочник районов по 1926 году';


-- -----------------------------------------------------
-- Table `selsovets1926`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `selsovets1926` ;

CREATE TABLE IF NOT EXISTS `selsovets1926` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
  `district1926_id` TINYINT UNSIGNED NOT NULL COMMENT 'district1926.id',
  `name_ru` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Russian name',
  `name_en` VARCHAR(150) NULL DEFAULT NULL COMMENT 'English name',
  `name_krl` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Karelian name',
  `wd` INT UNSIGNED NULL DEFAULT NULL COMMENT 'Wikidata identifier',
  PRIMARY KEY (`id`),
  INDEX `fk_DISTRICT1926_idx` (`district1926_id` ASC) VISIBLE,
  CONSTRAINT `fk_DISTRICT1926`
    FOREIGN KEY (`district1926_id`)
    REFERENCES `districts1926` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Справочник сельсоветов по 1926 году';


-- -----------------------------------------------------
-- Table `settlements1926`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `settlements1926` ;

CREATE TABLE IF NOT EXISTS `settlements1926` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `selsovet_id` TINYINT UNSIGNED NOT NULL COMMENT 'selsovets1926.id',
  `name_ru` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Russian name',
  `name_en` VARCHAR(150) NULL DEFAULT NULL COMMENT 'English name',
  `name_krl` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Karelian name',
  `wd` INT UNSIGNED NULL DEFAULT NULL COMMENT 'Wikidata identifier',
  PRIMARY KEY (`id`),
  INDEX `fk_SELSOVET1926_idx` (`selsovet_id` ASC) VISIBLE,
  CONSTRAINT `fk_SELSOVET1926`
    FOREIGN KEY (`selsovet_id`)
    REFERENCES `selsovets1926` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Справочник населенных пунктов по 1926 году';


-- -----------------------------------------------------
-- Table `geocategories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geocategories` ;

CREATE TABLE IF NOT EXISTS `geocategories` (
  `id` TINYINT(3) UNSIGNED NOT NULL COMMENT 'id',
  `short_ru` VARCHAR(32) NULL DEFAULT NULL COMMENT 'Short description in Russian',
  `name_ru` VARCHAR(64) NOT NULL COMMENT 'Name in Russian',
  `desc_ru` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Description in Russian',
  `short_en` VARCHAR(32) NULL DEFAULT NULL COMMENT 'Short description in English',
  `name_en` VARCHAR(64) NULL DEFAULT NULL COMMENT 'Name in English',
  `desc_en` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Description in English',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `short_ru_UNIQUE` (`short_ru` ASC) VISIBLE,
  UNIQUE INDEX `short_en_UNIQUE` (`short_en` ASC) VISIBLE,
  UNIQUE INDEX `name_en_UNIQUE` (`name_en` ASC) VISIBLE,
  UNIQUE INDEX `name_ru_UNIQUE` (`name_ru` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Metalevel of types of geographic objects.';


-- -----------------------------------------------------
-- Table `geotype_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geotype_category` ;

CREATE TABLE IF NOT EXISTS `geotype_category` (
  `id` TINYINT(3) UNSIGNED NOT NULL COMMENT 'id',
  `geotype_id` TINYINT(3) UNSIGNED NOT NULL COMMENT 'id',
  `geocategory_id` TINYINT(3) UNSIGNED NOT NULL COMMENT 'id',
  PRIMARY KEY (`id`),
  INDEX `type_category_idx` (`geotype_id` ASC, `geocategory_id` ASC) VISIBLE,
  INDEX `fk_geocategory_id_idx` (`geocategory_id` ASC) VISIBLE,
  CONSTRAINT `fk_geotype_id`
    FOREIGN KEY (`geotype_id`)
    REFERENCES `geotypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_geocategory_id`
    FOREIGN KEY (`geocategory_id`)
    REFERENCES `geocategories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Metalevel of types of geographic objects.';


-- -----------------------------------------------------
-- Table `structhiers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `structhiers` ;

CREATE TABLE IF NOT EXISTS `structhiers` (
  `id` TINYINT(3) UNSIGNED NOT NULL,
  `name_ru` VARCHAR(50) NOT NULL COMMENT 'Russian name',
  `name_en` VARCHAR(50) NULL COMMENT 'English name',
  `parent_id` TINYINT(3) UNSIGNED NULL COMMENT 'ID of parent in the same table',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Hierarchy tree of structures of toponyms';


-- -----------------------------------------------------
-- Table `structs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `structs` ;

CREATE TABLE IF NOT EXISTS `structs` (
  `id` SMALLINT(5) UNSIGNED NOT NULL,
  `structhier_id` TINYINT(3) UNSIGNED NULL COMMENT 'structhiers.id',
  `name_ru` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Russian name',
  `name_en` VARCHAR(150) NULL DEFAULT NULL COMMENT 'English name',
  PRIMARY KEY (`id`),
  INDEX `structhier_idx` (`structhier_id` ASC) VISIBLE,
  CONSTRAINT `fk_structshier`
    FOREIGN KEY (`structhier_id`)
    REFERENCES `structhiers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'toponyms structures';


-- -----------------------------------------------------
-- Table `etymology_nations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `etymology_nations` ;

CREATE TABLE IF NOT EXISTS `etymology_nations` (
  `id` TINYINT(3) UNSIGNED NOT NULL COMMENT 'id',
  `short_ru` VARCHAR(32) NULL DEFAULT NULL COMMENT 'Short description in Russian',
  `name_ru` VARCHAR(64) NOT NULL COMMENT 'Name in Russian',
  `short_en` VARCHAR(32) NULL DEFAULT NULL COMMENT 'Short description in English',
  `name_en` VARCHAR(64) NULL DEFAULT NULL COMMENT 'Name in English',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `short_ru_UNIQUE` (`short_ru` ASC) VISIBLE,
  UNIQUE INDEX `short_en_UNIQUE` (`short_en` ASC) VISIBLE,
  UNIQUE INDEX `name_en_UNIQUE` (`name_en` ASC) VISIBLE,
  UNIQUE INDEX `name_ru_UNIQUE` (`name_ru` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'National sign of etymology (Russians, Baltic-Finnish, Sami and obscure).';


-- -----------------------------------------------------
-- Table `ethnos_territories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ethnos_territories` ;

CREATE TABLE IF NOT EXISTS `ethnos_territories` (
  `id` TINYINT(3) UNSIGNED NOT NULL,
  `name_ru` VARCHAR(50) NOT NULL COMMENT 'Russian name',
  `name_en` VARCHAR(50) NULL DEFAULT NULL COMMENT 'English name',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Territory of settlement of ethnolocal groups of the population of Karelia ';


-- -----------------------------------------------------
-- Table `langs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `langs` ;

CREATE TABLE IF NOT EXISTS `langs` (
  `id` TINYINT(2) UNSIGNED NOT NULL,
  `name_en` VARCHAR(64) NOT NULL,
  `name_ru` VARCHAR(64) NOT NULL,
  `code` VARCHAR(3) NULL DEFAULT NULL COMMENT 'Name of toponym in Russian, or Karelian, or...',
  `sequence_number` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'toponyms - main table';


-- -----------------------------------------------------
-- Table `toponyms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toponyms` ;

CREATE TABLE IF NOT EXISTS `toponyms` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lang_id` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
  `district_id` TINYINT UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(256) NULL DEFAULT NULL COMMENT 'Name of toponym in Russian, or Karelian, or...',
  `name_for_search` VARCHAR(256) NULL DEFAULT NULL COMMENT 'Wikidata identifier',
  `settlement1926_id` SMALLINT UNSIGNED NULL,
  `geotype_id` TINYINT UNSIGNED NULL DEFAULT NULL COMMENT 'Type of geographic objects geotypes.id',
  `etymology_nation_id` TINYINT UNSIGNED NULL DEFAULT NULL COMMENT 'National sign of etymology, etymology_nations.id',
  `ethnos_territory_id` TINYINT UNSIGNED NULL DEFAULT NULL COMMENT 'Territory of ethno groups of Karelia, ethnos_territories.id',
  `caseform` VARCHAR(256) NULL DEFAULT NULL COMMENT 'Locative form.',
  `accent` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `transcription` VARCHAR(128) NULL DEFAULT NULL,
  `main_info` VARCHAR(8192) NULL DEFAULT NULL COMMENT 'Legend.',
  `etymology` VARCHAR(2048) NULL DEFAULT NULL,
  `latitude` DECIMAL(17,14) UNSIGNED NULL DEFAULT NULL,
  `longitude` DECIMAL(17,14) UNSIGNED NULL DEFAULT NULL,
  `MAP` TINYINT NULL DEFAULT NULL COMMENT 'boolean, 0 - absent, 1 means MAPSNOMENCLATURE has value.',
  `area` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Cell on a map (text)',
  `OBJNUM` VARCHAR(64) NULL DEFAULT NULL COMMENT 'Object number on the map.',
  `MAPSNOMENCLATURE` VARCHAR(128) NULL DEFAULT NULL,
  `source` VARCHAR(4096) NULL DEFAULT NULL,
  `folk` TEXT NULL,
  `legend` TEXT NULL,
  `wd` INT UNSIGNED NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_district_idx` (`district_id` ASC) VISIBLE,
  INDEX `fk_settlement1926_idx` (`settlement1926_id` ASC) VISIBLE,
  INDEX `fk_geotype_idx` (`geotype_id` ASC) VISIBLE,
  INDEX `fk_etymology_nation_idx` (`etymology_nation_id` ASC) VISIBLE,
  INDEX `fk_ethnos_territory_idx` (`ethnos_territory_id` ASC) VISIBLE,
  INDEX `fk_lang_idx` (`lang_id` ASC) VISIBLE,
  CONSTRAINT `fk_district`
    FOREIGN KEY (`district_id`)
    REFERENCES `districts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_settlement1926`
    FOREIGN KEY (`settlement1926_id`)
    REFERENCES `settlements1926` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_type`
    FOREIGN KEY (`geotype_id`)
    REFERENCES `geotypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etymology_nation`
    FOREIGN KEY (`etymology_nation_id`)
    REFERENCES `etymology_nations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ethnos_territory`
    FOREIGN KEY (`ethnos_territory_id`)
    REFERENCES `ethnos_territories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lang`
    FOREIGN KEY (`lang_id`)
    REFERENCES `langs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'toponyms - main table';


-- -----------------------------------------------------
-- Table `struct_toponym`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `struct_toponym` ;

CREATE TABLE IF NOT EXISTS `struct_toponym` (
  `struct_id` SMALLINT(5) UNSIGNED NOT NULL,
  `toponym_id` INT(10) UNSIGNED NOT NULL COMMENT 'Pivot of tables structs and toponyms',
  INDEX `struct_toponym_idx` (`struct_id` ASC, `toponym_id` ASC) VISIBLE,
  INDEX `toponym_idx` (`toponym_id` ASC) VISIBLE,
  PRIMARY KEY (`struct_id`, `toponym_id`),
  CONSTRAINT `fk_struct_id`
    FOREIGN KEY (`struct_id`)
    REFERENCES `structs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_toponym_id`
    FOREIGN KEY (`toponym_id`)
    REFERENCES `toponyms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Pivot of tables structs and toponyms';


-- -----------------------------------------------------
-- Table `settlement_toponym`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `settlement_toponym` ;

CREATE TABLE IF NOT EXISTS `settlement_toponym` (
  `settlement_id` SMALLINT(5) UNSIGNED NOT NULL,
  `toponym_id` INT(10) UNSIGNED NOT NULL,
  INDEX `settlement_idx` (`settlement_id` ASC) VISIBLE,
  INDEX `toponym_idx` (`toponym_id` ASC) VISIBLE,
  CONSTRAINT `fk_settlement`
    FOREIGN KEY (`settlement_id`)
    REFERENCES `settlements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_toponym`
    FOREIGN KEY (`toponym_id`)
    REFERENCES `toponyms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `NOMENCLATURE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NOMENCLATURE` ;

CREATE TABLE IF NOT EXISTS `NOMENCLATURE` (
  `ethnos_territory_id` TINYINT UNSIGNED NOT NULL,
  `MAPSNOMENCLATURE` VARCHAR(128) NOT NULL,
  INDEX `fk_ethnos_territory_id_idx` (`ethnos_territory_id` ASC) VISIBLE,
  CONSTRAINT `fk_ethnos_territory_id`
    FOREIGN KEY (`ethnos_territory_id`)
    REFERENCES `ethnos_territories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Map cell to a territory in  the table ethnos_territories.';


-- -----------------------------------------------------
-- Table `topnames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `topnames` ;

CREATE TABLE IF NOT EXISTS `topnames` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `toponym_id` INT UNSIGNED NULL DEFAULT NULL,
  `lang_id` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(256) NULL DEFAULT NULL COMMENT 'Name of toponym in Russian, or Karelian, or...',
  `name_for_search` VARCHAR(256) NULL DEFAULT NULL COMMENT 'Wikidata identifier',
  PRIMARY KEY (`id`),
  INDEX `fk_toponym_idx` (`lang_id` ASC) VISIBLE,
  CONSTRAINT `fk_toponym`
    FOREIGN KEY (`lang_id`)
    REFERENCES `toponyms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lang`
    FOREIGN KEY (`lang_id`)
    REFERENCES `langs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'toponyms - main table';


-- -----------------------------------------------------
-- Table `sources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sources` ;

CREATE TABLE IF NOT EXISTS `sources` (
  `id` TINYINT(3) UNSIGNED NOT NULL COMMENT 'id',
  `short_ru` VARCHAR(32) NULL DEFAULT NULL COMMENT 'Short description in Russian',
  `name_ru` VARCHAR(64) NOT NULL COMMENT 'Name in Russian',
  `short_en` VARCHAR(32) NULL DEFAULT NULL COMMENT 'Short description in English',
  `name_en` VARCHAR(64) NULL DEFAULT NULL COMMENT 'Name in English',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `short_ru_UNIQUE` (`short_ru` ASC) VISIBLE,
  UNIQUE INDEX `short_en_UNIQUE` (`short_en` ASC) VISIBLE,
  UNIQUE INDEX `name_en_UNIQUE` (`name_en` ASC) VISIBLE,
  UNIQUE INDEX `name_ru_UNIQUE` (`name_ru` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Types of geographic objects (geo features).';


-- -----------------------------------------------------
-- Table `toponym_source`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `toponym_source` ;

CREATE TABLE IF NOT EXISTS `toponym_source` (
  `id` INT(10) UNSIGNED NOT NULL,
  `toponym_id` INT(10) UNSIGNED NOT NULL,
  `mention` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Name of toponym in Russian, or Karelian, or...',
  `source_id` TINYINT(3) UNSIGNED NULL,
  `source_text` VARCHAR(256) NOT NULL COMMENT 'Wikidata identifier',
  `sequence_number` SMALLINT(6) NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_toponym_idx` (`toponym_id` ASC) VISIBLE,
  INDEX `fk_source_idx` (`source_id` ASC) VISIBLE,
  CONSTRAINT `fk_toponym0`
    FOREIGN KEY (`toponym_id`)
    REFERENCES `toponyms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_source`
    FOREIGN KEY (`source_id`)
    REFERENCES `sources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'toponyms - main table';


-- -----------------------------------------------------
-- Table `events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `events` ;

CREATE TABLE IF NOT EXISTS `events` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `toponym_id` INT(10) UNSIGNED NOT NULL,
  `date` SMALLINT(5) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_toponym_id_idx` (`toponym_id` ASC) VISIBLE,
  CONSTRAINT `fk_toponym_id`
    FOREIGN KEY (`toponym_id`)
    REFERENCES `toponyms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `event_informant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_informant` ;

CREATE TABLE IF NOT EXISTS `event_informant` (
  `event_id` INT(10) UNSIGNED NOT NULL,
  `informant_id` SMALLINT(5) UNSIGNED NOT NULL,
  INDEX `settlement_idx` (`event_id` ASC) VISIBLE,
  INDEX `toponym_idx` (`informant_id` ASC) VISIBLE,
  PRIMARY KEY (`event_id`, `informant_id`),
  CONSTRAINT `fk_event_id`
    FOREIGN KEY (`event_id`)
    REFERENCES `events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_informant_id`
    FOREIGN KEY (`informant_id`)
    REFERENCES `informants` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `event_recorder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_recorder` ;

CREATE TABLE IF NOT EXISTS `event_recorder` (
  `event_id` INT(10) UNSIGNED NOT NULL,
  `recorder_id` SMALLINT(5) UNSIGNED NOT NULL,
  INDEX `settlement_idx` (`event_id` ASC) VISIBLE,
  INDEX `toponym_idx` (`recorder_id` ASC) VISIBLE,
  PRIMARY KEY (`event_id`, `recorder_id`),
  CONSTRAINT `fk_event_id0`
    FOREIGN KEY (`event_id`)
    REFERENCES `events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recorder_id0`
    FOREIGN KEY (`recorder_id`)
    REFERENCES `recorders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `event_settlement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_settlement` ;

CREATE TABLE IF NOT EXISTS `event_settlement` (
  `event_id` INT(10) UNSIGNED NOT NULL,
  `settlement_id` SMALLINT(5) UNSIGNED NOT NULL,
  INDEX `settlement_idx` (`event_id` ASC) VISIBLE,
  INDEX `toponym_idx` (`settlement_id` ASC) VISIBLE,
  PRIMARY KEY (`event_id`, `settlement_id`),
  CONSTRAINT `fk_event_id00`
    FOREIGN KEY (`event_id`)
    REFERENCES `events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_setllement_id00`
    FOREIGN KEY (`settlement_id`)
    REFERENCES `settlements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `wrongnames`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wrongnames` ;

CREATE TABLE IF NOT EXISTS `wrongnames` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `toponym_id` INT UNSIGNED NULL DEFAULT NULL,
  `lang_id` TINYINT(2) UNSIGNED NULL DEFAULT NULL,
  `name` VARCHAR(256) NULL DEFAULT NULL COMMENT 'Name of toponym in Russian, or Karelian, or...',
  `name_for_search` VARCHAR(256) NULL DEFAULT NULL COMMENT 'Wikidata identifier',
  PRIMARY KEY (`id`),
  INDEX `fk_toponym_idx` (`lang_id` ASC) VISIBLE,
  CONSTRAINT `fk_toponym1`
    FOREIGN KEY (`lang_id`)
    REFERENCES `toponyms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lang0`
    FOREIGN KEY (`lang_id`)
    REFERENCES `langs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'toponyms - main table';


-- -----------------------------------------------------
-- Table `event_settlement1926`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `event_settlement1926` ;

CREATE TABLE IF NOT EXISTS `event_settlement1926` (
  `event_id` INT(10) UNSIGNED NOT NULL,
  `settlement1926_id` SMALLINT(5) UNSIGNED NOT NULL,
  INDEX `settlement_idx` (`event_id` ASC) VISIBLE,
  INDEX `toponym_idx` (`settlement1926_id` ASC) VISIBLE,
  PRIMARY KEY (`event_id`, `settlement1926_id`),
  CONSTRAINT `fk_event_id000`
    FOREIGN KEY (`event_id`)
    REFERENCES `events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_settlement1926`
    FOREIGN KEY (`settlement1926_id`)
    REFERENCES `settlements1926` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `streets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `streets` ;

CREATE TABLE IF NOT EXISTS `streets` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name_ru` VARCHAR(150) NULL DEFAULT NULL,
  `name_krl` VARCHAR(150) NULL DEFAULT NULL,
  `name_fi` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Name of toponym in Russian, or Karelian, or...',
  `name_for_search_ru` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Wikidata identifier',
  `name_for_search_krl` VARCHAR(150) NULL,
  `name_for_search_krl` VARCHAR(150) NULL DEFAULT NULL COMMENT 'Type of geographic objects geotypes.id',
  `geotype_id` SMALLINT(5) UNSIGNED NULL DEFAULT NULL COMMENT 'National sign of etymology, etymology_nations.id',
  `history` TEXT NULL DEFAULT NULL COMMENT 'Territory of ethno groups of Karelia, ethnos_territories.id',
  `main_info` VARCHAR(8192) NULL DEFAULT NULL COMMENT 'Legend.',
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_geotype_id_idx` (`geotype_id` ASC) VISIBLE,
  CONSTRAINT `fk_geotype_id`
    FOREIGN KEY (`geotype_id`)
    REFERENCES `geotypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'toponyms - main table';


-- -----------------------------------------------------
-- Table `street_struct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `street_struct` ;

CREATE TABLE IF NOT EXISTS `street_struct` (
  `street_id` INT(10) UNSIGNED NOT NULL COMMENT 'Pivot of tables structs and toponyms',
  `struct_id` SMALLINT(5) UNSIGNED NOT NULL,
  INDEX `struct_toponym_idx` (`struct_id` ASC, `street_id` ASC) VISIBLE,
  PRIMARY KEY (`street_id`, `struct_id`),
  CONSTRAINT `fk_struct_id0`
    FOREIGN KEY (`struct_id`)
    REFERENCES `structs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_street_id0`
    FOREIGN KEY (`street_id`)
    REFERENCES `streets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Pivot of tables structs and toponyms';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
